CREATE TABLE addresses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street       VARCHAR(100)                            NOT NULL,
    city         VARCHAR(100),
    postal_code  VARCHAR(100),
    country      VARCHAR(100),
    country_code VARCHAR(2),
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(100),
    last_name   VARCHAR(100),
    email       VARCHAR(255),
    phone       VARCHAR(20),
    nationality VARCHAR(100),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE emergency_contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(100),
    last_name    VARCHAR(100),
    relationship VARCHAR(255),
    phone        VARCHAR(20),
    CONSTRAINT pk_emergency_contacts PRIMARY KEY (id)
);

CREATE TABLE itinerary
(
    travel_info_id BIGINT NOT NULL,
    item           VARCHAR(15)
);

CREATE TABLE tourist_sheets
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    customer_id          BIGINT,
    address_id           BIGINT,
    travel_info_id       BIGINT,
    emergency_contact_id BIGINT,
    created_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT pk_tourist_sheets PRIMARY KEY (id)
);

CREATE TABLE travel_infos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    travel_start_date date                                    NOT NULL,
    travel_end_date   date                                    NOT NULL,
    flight_details    VARCHAR(100),
    CONSTRAINT pk_travel_infos PRIMARY KEY (id)
);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT FK_TOURIST_SHEETS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT FK_TOURIST_SHEETS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT FK_TOURIST_SHEETS_ON_EMERGENCY_CONTACT FOREIGN KEY (emergency_contact_id) REFERENCES emergency_contacts (id);

ALTER TABLE tourist_sheets
    ADD CONSTRAINT FK_TOURIST_SHEETS_ON_TRAVEL_INFO FOREIGN KEY (travel_info_id) REFERENCES travel_infos (id);

ALTER TABLE itinerary
    ADD CONSTRAINT fk_itinerary_on_travel_info FOREIGN KEY (travel_info_id) REFERENCES travel_infos (id);